// Code generated by 'yaegi extract hibike'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package lib

import (
	"github.com/5rahim/hibike/pkg/extension/utils"
	"reflect"
)

func init() {
	Symbols["github.com/5rahim/hibike/pkg/extension/utils"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddCloudFlareByPass":           reflect.ValueOf(utils.AddCloudFlareByPass),
		"CompareWithSorensenDice":       reflect.ValueOf(utils.CompareWithSorensenDice),
		"FindBestMatchWithSorensenDice": reflect.ValueOf(utils.FindBestMatchWithSorensenDice),
		"GetDefaultOptions":             reflect.ValueOf(utils.GetDefaultOptions),
		"Reverse":                       reflect.ValueOf(utils.Reverse),

		// type definitions
		"Options":            reflect.ValueOf((*utils.Options)(nil)),
		"SorensenDiceResult": reflect.ValueOf((*utils.SorensenDiceResult)(nil)),
	}
}
