// Code generated by 'yaegi extract hibike'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package lib

import (
	"github.com/5rahim/hibike/pkg/extension/manga"
	"reflect"
)

func init() {
	Symbols["github.com/5rahim/hibike/pkg/extension/manga"] = map[string]reflect.Value{
		// type definitions
		"ChapterDetails": reflect.ValueOf((*manga.ChapterDetails)(nil)),
		"ChapterPage":    reflect.ValueOf((*manga.ChapterPage)(nil)),
		"Provider":       reflect.ValueOf((*manga.Provider)(nil)),
		"SearchOptions":  reflect.ValueOf((*manga.SearchOptions)(nil)),
		"SearchResult":   reflect.ValueOf((*manga.SearchResult)(nil)),

		// interface wrapper definitions
		"_Provider": reflect.ValueOf((*_hibike_Provider)(nil)),
	}
}

// _hibike_Provider is an interface wrapper for Provider type
type _hibike_Provider struct {
	IValue            interface{}
	WFindChapterPages func(id string) ([]*manga.ChapterPage, error)
	WFindChapters     func(id string) ([]*manga.ChapterDetails, error)
	WSearch           func(opts manga.SearchOptions) ([]*manga.SearchResult, error)
}

func (W _hibike_Provider) FindChapterPages(id string) ([]*manga.ChapterPage, error) {
	return W.WFindChapterPages(id)
}
func (W _hibike_Provider) FindChapters(id string) ([]*manga.ChapterDetails, error) {
	return W.WFindChapters(id)
}
func (W _hibike_Provider) Search(opts manga.SearchOptions) ([]*manga.SearchResult, error) {
	return W.WSearch(opts)
}
